export const LOGIN = 'LOGIN'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'
export const CLEAR_STATUS = 'CLEAR_STATUS'
